# Generated by Django 3.2.8 on 2021-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20211027_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', editable=False, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
